### ISSUE TITLE
Maybe make use of SunCalc?

### ISSUE THREAD

**Issue by pjerem** [codeimpossible/sunset#2]
Hi,

You made a nice Atom module.

Maybe can i suggest you to use https://github.com/mourner/suncalc . This would allow to automatically set sunset and sunrise times based on geographical position of the user.

Have a nice day !

ps: please excuse my poor grammar since English is not my native language :) (since it's javascript)

**Comment by codeimpossible** [comment]
@pjerem whoa thats pretty cool. I wonder if atom has support for html5 location API... something to look into i guess. Thanks for the recommendation!

**Comment by zap0xfce2** [comment]
Please add the suncalc! An alternative would be to add a different time schedule for winter or summer months ;)

**Comment by FlorianWendelborn** [comment]
@zap0xfce2 This won't solve the issue for those of us who travel.

**Comment by FlorianWendelborn** [comment]
@codeimpossible Thank you for fixing this, you just made the world a better place, one line at a time.
