### ISSUE TITLE
How do I configure themes?

### ISSUE THREAD

**Issue by austin-thesing** [codeimpossible/sunset#3]
Where do I go to enter the theme names and times for switching

**Comment by codeimpossible** [comment]
Hey @austin-thesing, after you install sunset, go to your settings in Atom (cmd+, or ctrl+, on windows). Then click "Packages" in the left-hand tab bar that appears, scroll down until you see the sunset package and click "Configure". That should show you configuration page so you can change the options.

Hope this helps!

**Comment by sergiopvilar** [comment]
@codeimpossible there's no configuration page yet, you said yourself in the README.

**Comment by philippeowagner** [comment]
After restarting Atom the "Settings" button showed up. Nice plugin @codeimpossible – thank you!
